version: '3.7'

services:
  app:
    image: letssudormrf/v2ray-docker:latest
    environment:
      - UUID=f7326e15-2909-46c6-bea3-7dbd5eebcb21
      - WSPATH=/home/
    networks:
      default:
      swarm_routing:
        aliases:
          - app.example.com
    deploy:
#      resources:
#        reservations:
#          cpus: '0.05'
#          memory: 8M
#        limits:
#          memory: 8M
#      mode: replicated
#      replicas: 1
      mode: global
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 10

networks:
  default:
    internal: true
    driver: overlay
  swarm_routing:
    external: true
